version: '3'
volumes:
  vendor:
services:
  api:
    image: golang:latest
    container_name: go_container
    command: go run go/api.go
    environment: 
      - GOPATH=
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/go
  app:
    build: .
    command: sh -c "yarn --force && yarn run serve"
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - "8000:8080"
