version: '3'
volumes:
  vendor:
services:
  app: &app
    build: .
    command: sh -c "yarn --force && yarn run serve"
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - "8000:8080"
  api:
    <<: *app
    container_name: go_container
    command: sh -c "GIN_MODE=release ./go-app/main"
    environment: 
      - GOPATH=
    tty: true
    ports:
      - "3000:3000"
